### ISSUE TITLE
DO57 As a data owner I would like that any MNR data outputs have the right caveats so that users can make use of the data adequately

### ISSUE THREAD

**Issue by scsmendes** [jncc/marine-noise-registry#220] opened 2021-08-19 09:35 UTC
particularly important for the proposed data
overlap with #203

**Comment by LynnHeeley** [comment] 2021-08-19 15:15
duplicate?

**Comment by LynnHeeley** [comment] 2021-08-25 07:40
duplicate of #203 , rejected and closed

**Closed by LynnHeeley** 2021-08-25 07:40 UTC
Labels: duplicate, data user, data owner, rejected
